# Generated by Django 5.1.7 on 2025-03-31 09:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmember",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardmember",
            unique_together={("board", "user")},
        ),
    ]
