# Generated by Django 5.1.7 on 2025-04-01 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_boardmember_joined_at_alter_boardmember_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmember",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="board.board",
            ),
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
