# Generated by Django 5.1.7 on 2025-04-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="column",
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="position",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Column",
        ),
    ]
